version: '3.2'

services:
  frontender:
    build:
      context: ../frontender.info
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
  article:
    build:
      context: ../article.frontender.info
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
  token:
    build:
      context: ../token.frontender.info
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
  user:
    build:
      context: ../user.frontender.info
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
  schedule:
    build:
      context: ../schedule.frontender.info
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

networks:
    backend:

volumes:
    redis:
    mongo: