version: "3.2"

services:
  frontender:
    image: frontendermagazine/frontender:latest
    expose:
      - "4000"
    volumes:
      - "./.env:/var/.env"
    networks:
      - backend
    depends_on:
      - mongodb
    environment:
      WEB_PORTS: "80 443"
      VIRTUAL_HOST: "frontend.events"
      VIRTUAL_PORT: 4000
  article:
    image: frontendermagazine/article:latest
    volumes:
      - "./.env:/var/.env"
    networks:
      - backend
    depends_on:
      - mongodb
    expose:
      - "4000"
    environment:
      WEB_PORTS: "80 443"
      VIRTUAL_HOST: "article.frontend.events"
      VIRTUAL_PORT: 4000
  token:
    image: frontendermagazine/token:latest
    volumes:
      - "./.env:/var/app/.env"
    networks:
      - backend
    depends_on:
      - mongodb
    ports:
      - "6000:4000"
    expose:
      - "4000"
    environment:
      WEB_PORTS: "80 443"
      VIRTUAL_HOST: "token.frontend.events"
      VIRTUAL_PORT: 4000
  user:
    image: frontendermagazine/user:latest
    volumes:
      - "./.env:/var/app/.env"
    networks:
      - backend
    depends_on:
      - mongodb
    expose:
      - "4000"
    environment:
      WEB_PORTS: "80 443"
      VIRTUAL_HOST: "user.frontend.events"
      VIRTUAL_PORT: 4000
  schedule:
    image: frontendermagazine/schedule:latest
    expose:
      - "4000"
    volumes:
      - "./.env:/var/app/.env"
    networks:
      - backend
    depends_on:
      - mongodb
    environment:
      WEB_PORTS: "80 443"
      VIRTUAL_HOST: "schedule.frontend.events"
      VIRTUAL_PORT: 4000
  mongodb:
    image: "mongo:latest"
    networks:
      - backend
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
  web:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DEFAULT_HOST=frontend.events
    networks:
      - backend
  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300

networks:
  backend:

volumes:
  mongo:
