version: '3.2'

services:
  frontender:
    image: frontendermagazine/frontender:latest
    expose:
      - "4000" 
    volumes:
      - './configs/.env:/var/.env'
      - './configs/application.production.json:/var/app/config/application.production.json'
    networks:
      - backend
    depends_on:
      - mongodb
    environment:
      WEB_PORTS: "80 443"
      VIRTUAL_HOST: "frontend.events"
      VIRTUAL_PORT: 4000
  article:
    image: frontendermagazine/article:latest
    volumes:
      - './configs/.env:/var/.env'
      - './configs/application.production.json:/var/app/config/application.production.json'
    networks:
      - backend
    depends_on:
      - mongodb
      - redis
    expose:
      - "4000"   
    environment:
      WEB_PORTS: "80 443"
      VIRTUAL_HOST: "article.frontend.events"
      VIRTUAL_PORT: 4000
  token:
    image: frontendermagazine/token:latest
    volumes:
      - './configs/.env:/var/app/.env'
      - './configs/application.token.production.json:/var/app/config/application.production.json'
    networks:
      - backend
    depends_on:
      - mongodb
      - redis
    ports:
      - "6000:4000"
    expose:
      - "4000"   
    environment:
      WEB_PORTS: "80 443"
      VIRTUAL_HOST: "token.frontend.events"
      VIRTUAL_PORT: 4000
  user:
    image: frontendermagazine/user:latest
    volumes:
      - './configs/.env:/var/app/.env'
      - './configs/application.production.json:/var/app/config/application.production.json'
    networks:
      - backend
    depends_on:
      - mongodb
      - redis
    expose:
      - "4000"   
    environment:
      WEB_PORTS: "80 443"
      VIRTUAL_HOST: "user.frontend.events"
      VIRTUAL_PORT: 4000
  schedule:
    image: frontendermagazine/schedule:latest
    expose:
      - "4000"
    volumes:
      - './configs/.env:/var/.env'
      - './configs/application.schedule.production.json:/var/app/config/application.production.json'
    networks:
      - backend
    depends_on:
      - mongodb
      - redis
    environment:
      WEB_PORTS: "80 443"
      VIRTUAL_HOST: "schedule.frontend.events"
      VIRTUAL_PORT: 4000 
  redis:
    image: 'redis:alpine'
    environment:
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    networks:
      - backend
    volumes:
      - 'redis:/etc/redis/database/caesarapp'
  mongodb:
    image: 'mongo:latest'
    networks:
      - backend
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
  web:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro  
    environment:
      - DEFAULT_HOST=frontend.events 
    networks:
      - backend  
  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300
    
networks:
    backend:

volumes:
    redis:
    mongo:
