version: "3.2"

services:
  rabbitmq:
    image: rabbitmq
    command: rabbitmq-server
    expose:
      - 5672
      - 15672
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "check_running"]
      interval: 5s
      timeout: 15s
      retries: 3
  frontender:
    image: frontendermagazine/frontender:latest
    expose:
      - "3000"
    volumes:
      - '../.env:/var/app/.env'
      - type: bind
        source: /websites/frontender.info
        target: /var/app/static
      - type: bind
        source: /websites/articles
        target: /websites/articles
    networks:
      - backend
    depends_on:
      - mongodb
    environment:
      WEB_PORTS: "80 443"
      VIRTUAL_HOST: "${DEFAULT_HOST}"
      VIRTUAL_PORT: 3000
  analyze:
    image: frontendermagazine/analyze:latest
    volumes:
      - '../.env:/var/app/.env'
    networks:
      - backend
    depends_on:
      - rabbitmq
  article:
    image: frontendermagazine/article:latest
    volumes:
      - '../.env:/var/app/.env'
    networks:
      - backend
    depends_on:
      - mongodb
      - rabbitmq
    expose:
      - "3000"
    environment:
      WEB_PORTS: "80 443"
      VIRTUAL_HOST: "article.${DEFAULT_HOST}"
      VIRTUAL_PORT: 3000
  token:
    image: frontendermagazine/token:latest
    volumes:
      - '../.env:/var/app/.env'
    networks:
      - backend
    depends_on:
      - mongodb
    expose:
      - "3000"
    environment:
      WEB_PORTS: "80 443"
      VIRTUAL_HOST: "token.${DEFAULT_HOST}"
      VIRTUAL_PORT: 3000
  user:
    image: frontendermagazine/user:latest
    volumes:
      - '../.env:/var/app/.env'
    networks:
      - backend
    depends_on:
      - mongodb
    expose:
      - "3000"
    environment:
      WEB_PORTS: "80 443"
      VIRTUAL_HOST: "user.${DEFAULT_HOST}"
      VIRTUAL_PORT: 3000
  mailparser:
    image: frontendermagazine/mailparser:latest
    volumes:
      - '../.env:/var/app/.env'
    networks:
      - backend
    depends_on:
      - rabbitmq
    expose:
      - "3000"
    environment:
      WEB_PORTS: "80 443"
      VIRTUAL_HOST: "mailparser.${DEFAULT_HOST}"
      VIRTUAL_PORT: 3000
  schedule:
    image: frontendermagazine/schedule:latest
    expose:
      - "3000"
    volumes:
      - '../.env:/var/app/.env'
    networks:
      - backend
    depends_on:
      - mongodb
    environment:
      WEB_PORTS: "80 443"
      VIRTUAL_HOST: "schedule.${DEFAULT_HOST}"
      VIRTUAL_PORT: 3000

  mongodb:
    image: "mongo:latest"
    networks:
      - backend
    volumes:
      - mongo:/data/db
  web:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DEFAULT_HOST=${DEFAULT_HOST}
    depends_on:
      - frontender
      - article
      - token
      - schedule
      - user
      - mailparser
      - rabbitmq
      - analyze
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - '../favicon.ico:/websites/common/favicon.ico'
      - type: bind
        source: /websites/ssl
        target: /websites/ssl
      - type: bind
        source: /websites/articles
        target: /websites/articles
      - type: bind
        source: /websites/frontender.info
        target: /websites/frontender.info

    networks:
      - backend

networks:
  backend:

volumes:
  mongo:
