version: "3.8"

services:
  frontender:
    build:
      context: ../frontender.info
  article:
    build:
      context: ../article.frontender.info
  token:
    build:
      context: ../token.frontender.info
  user:
    build:
      context: ../user.frontender.info
  schedule:
    build:
      context: ../schedule.frontender.info
  analyze:
    build:
      context: ../analyze.frontender.info
  mailparser:
    build:
      context: ../mailparser.frontender.info
  mongodb:
    ports:
      - "27017:27017"
