version: "3.2"

services:
  frontender:
    image: frontendermagazine/frontender:latest
    expose:
      - "${PORT}"
    volumes:
      - '.env:/var/app/.env'
    networks:
      - backend
    depends_on:
      - mongodb
    environment:
      WEB_PORTS: "80 443"
      VIRTUAL_HOST: "${DEFAULT_HOST}"
      VIRTUAL_PORT: ${PORT}
  article:
    image: frontendermagazine/article:latest
    volumes:
      - '.env:/var/app/.env'
    networks:
      - backend
    depends_on:
      - mongodb
    expose:
      - "${PORT}"
    environment:
      WEB_PORTS: "80 443"
      VIRTUAL_HOST: "article.${DEFAULT_HOST}"
      VIRTUAL_PORT: ${PORT}
  token:
    image: frontendermagazine/token:latest
    volumes:
      - '.env:/var/app/.env'
    networks:
      - backend
    depends_on:
      - mongodb
    expose:
      - "${PORT}"
    environment:
      WEB_PORTS: "80 443"
      VIRTUAL_HOST: "token.${DEFAULT_HOST}"
      VIRTUAL_PORT: ${PORT}
  user:
    image: frontendermagazine/user:latest
    volumes:
      - '.env:/var/app/.env'
    networks:
      - backend
    depends_on:
      - mongodb
    expose:
      - "${PORT}"
    environment:
      WEB_PORTS: "80 443"
      VIRTUAL_HOST: "user.${DEFAULT_HOST}"
      VIRTUAL_PORT: ${PORT}
  schedule:
    image: frontendermagazine/schedule:latest
    expose:
      - "${PORT}"
    volumes:
      - '.env:/var/app/.env'
    networks:
      - backend
    depends_on:
      - mongodb
    environment:
      WEB_PORTS: "80 443"
      VIRTUAL_HOST: "schedule.${DEFAULT_HOST}"
      VIRTUAL_PORT: ${PORT}
  mongodb:
    image: "mongo:latest"
    networks:
      - backend
    volumes:
      - mongo:/data/db
  web:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DEFAULT_HOST=${DEFAULT_HOST}
    networks:
      - backend
  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300

networks:
  backend:

volumes:
  mongo:
